### ISSUE TITLE
Setopt and Getopt are MIA

### ISSUE THREAD

**Issue by gdamore** [lthibault/quic-mangos#3]
The ability to set options for TLS at least, needs to be implemented before this would be a viable candidate for inclusion in mangos.

**Comment by lthibault** [comment]
Whoops, you're right.  This should be an easy fix, though!

**Comment by lthibault** [comment]
Options for TLS and QUIC can now be set/retrieved with `OptionTLSConfig` (expects a `*tls.Config`) and `OptionQUICConfig` (expects a `*quic.Config`).
