### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wllenyj** [lthibault/quic-mangos#4]
lthibault/quic-mangos/listener.go:31:13: undefined: ctx.Lift

**Comment by lthibault** [comment]
Should be fixed -- thanks!

We recently changed the public API of github.com/SentimensRG/ctx.  `ctx.Lift` was replaced with `ctx.C`.

Out of curiosity, what is your use-case for quic-mangos?

Let me know if you run into any trouble.

**Comment by wllenyj** [comment]
study  :-P

**Comment by lthibault** [comment]
Fair enough :)

In that case, I encourage you to have a look at https://github.com/lthibault/quic-mangos/issues/2.  I learned a few things about network protocol best-practices from gdamore's comments (e.g.:  prefer fixed-length headers to line-based protocols).

The fixes for the above issue are quite simple, yet make for an excellent study of mangos transport design.  If you're interested in taking a stab at it, I'd be happy to guide you along the path ;)
